# Generated by Django 5.1.7 on 2025-04-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="course",
            field=models.ManyToManyField(
                related_name="reviewscourse", to="courses.course"
            ),
        ),
    ]
